### PR TITLE
Error raise on 0% of the forecast work

### PR DESCRIPTION
**Pull request by aryanbhosale**
# Pull Request

## Description

_Please delete the italicised instruction text!
Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context. List any dependencies that are required for this change._

Fixes #

## How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration_

- [ ] Yes

_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_

- [ ] Yes

## Checklist:

- [ ] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by peterdudfield — APPROVED** [review]

**Comment by peterdudfield** [comment]
Ill just merge this to `development` so the tests can run

**Comment by peterdudfield** [comment]
Thank you @aryanbhosale for doing this work

**Comment by aryanbhosale** [comment]
> Thank you @aryanbhosale for doing this work

My pleasure @peterdudfield ! I'm actually starting off as an open source newbie, found openclimatefix to be doing something very different from the general organizations - there is a cause. I would like to apply to openclimatefix for this year's gsoc. Would you like to mentor me? I want to solve bigger issues
Thank you

**Comment by peterdudfield** [comment]
> > Thank you @aryanbhosale for doing this work
> 
> My pleasure @peterdudfield ! I'm actually starting off as an open source newbie, found openclimatefix to be doing something very different from the general organizations - there is a cause. I would like to apply to openclimatefix for this year's gsoc. Would you like to mentor me? I want to solve bigger issues Thank you

Yea, of course, I'm happy to be your mentor

**Comment by aryanbhosale** [comment]
> > > Thank you @aryanbhosale for doing this work
> > 
> > 
> > My pleasure @peterdudfield ! I'm actually starting off as an open source newbie, found openclimatefix to be doing something very different from the general organizations - there is a cause. I would like to apply to openclimatefix for this year's gsoc. Would you like to mentor me? I want to solve bigger issues Thank you
> 
> Yea, of course, I'm happy to be your mentor

Thank you so much! Will keep working on more issues in the upcoming days.

**Pull request merged**
